// generated by src/scripts/write-version-info.sh
package org.apache.sqoop;

public class SqoopVersion {
  public SqoopVersion() {
  }

  public static final String VERSION="1.5.0-SNAPSHOT";
  public static final String GIT_HASH="c9c07b2e8eabfb2066187c42a4d533e29ceded6c";
  public static final String COMPILE_USER="luping";
  public static final String COMPILE_DATE="2017年 9月21日 星期四 15时48分37秒 CST";

  @Override
  public String toString() {
    return "Sqoop " + VERSION + "\n"
        + "git commit id " + GIT_HASH + "\n"
        + "Compiled by " + COMPILE_USER
        + " on " + COMPILE_DATE + "\n";
  }
}
